OCR_SPACE_API_KEY = "K85301890588957" 
OPENAI_API_KEY = "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"
